export const CharacterIds = [
    'Captain Falcon',
    'Donkey Kong',
    'Fox',
    'Mr. Game and Watch',
    'Kirby',
    'Bowser',
    'Link',
    'Luigi',
    'Mario',
    'Marth',
    'Mewtwo',
    'Ness',
    'Peach',
    'Pikachu',
    'Ice Climbers',
    'Jigglypuff',
    'Samus',
    'Yoshi',
    'Zelda',
    'Sheik',
    'Falco',
    'Young Link',
    'Dr. Mario',
    'Roy',
    'Pichu',
    'Ganondorf'
];