export enum Character {
  DrMario = "Dr. Mario",
  Mario = "Mario",
  Luigi = "Luigi",
  Bowser = "Bowser",
  Peach = "Peach",
  Yoshi = "Yoshi",
  DK = "Donkey Kong",
  Falcon = "Captain Falcon",
  Ganondorf = "Ganondorf",
  Falco = "Falco",
  Fox = "Fox",
  Ness = "Ness",
  IC = "Ice Climbers",
  Kirby = "Kirby",
  Samus = "Samus",
  Zelda = "Zelda",
  Sheik = "Sheik",
  Link = "Link",
  YLink = "Young Link",
  Pichu = "Pichu",
  Pikachu = "Pikachu",
  Jigglypuff = "Jigglypuff",
  Mewtwo = "Mewtwo",
  GAW = "Mr. Game & Watch",
  Marth = "Marth",
  Roy = "Roy",
}

export const AllCharacters: Character[] = [
  Character.DrMario,
  Character.Mario,
  Character.Luigi,
  Character.Bowser,
  Character.Peach,
  Character.Yoshi,
  Character.DK,
  Character.Falcon,
  Character.Ganondorf,
  Character.Falco,
  Character.Fox,
  Character.Ness,
  Character.IC,
  Character.Kirby,
  Character.Samus,
  Character.Zelda,
  Character.Sheik,
  Character.Link,
  Character.YLink,
  Character.Pichu,
  Character.Pikachu,
  Character.Jigglypuff,
  Character.Mewtwo,
  Character.GAW,
  Character.Marth,
  Character.Roy,
];

export const Spacies: Character[] = [
  Character.Falcon,
  Character.Falco,
  Character.Fox,
];

export const Floaties: Character[] = [
  Character.DrMario,
  Character.Mario,
  Character.Luigi,
  Character.Bowser,
  Character.Peach,
  Character.Yoshi,
  Character.DK,
  Character.Ganondorf,
  Character.Ness,
  Character.IC,
  Character.Kirby,
  Character.Samus,
  Character.Zelda,
  Character.Sheik,
  Character.Link,
  Character.YLink,
  Character.Pichu,
  Character.Pikachu,
  Character.Jigglypuff,
  Character.Mewtwo,
  Character.GAW,
  Character.Marth,
  Character.Roy,
];

export const MidLowTiers: Character[] = [
  Character.DrMario,
  Character.Mario,
  Character.Luigi,
  Character.Bowser,
  Character.DK,
  Character.Ganondorf,
  Character.Ness,
  Character.Kirby,
  Character.Samus,
  Character.Zelda,
  Character.Link,
  Character.YLink,
  Character.Pichu,
  Character.Pikachu,
  Character.Mewtwo,
  Character.GAW,
  Character.Roy,
];
