export enum Character {
  DrMario = "Dr. Mario", 
  Mario = "Mario", 
  Luigi = "Luigi", 
  Bowser = "Bowser", 
  Peach = "Peach", 
  Yoshi = "Yoshi", 
  DK = "Donkey Kong", 
  Falcon = "Captain Falcon", 
  Ganondorf = "Ganondorf", 
  Falco = "Falco", 
  Fox = "Fox", 
  Ness = "Ness", 
  IC = "Ice Climbers", 
  Kirby = "Kirby", 
  Samus = "Samus", 
  Zelda = "Zelda", 
  Sheik = "Sheik", 
  Link = "Link", 
  YLink = "Young Link", 
  Pichu = "Pichu", 
  Pikachu = "Pikachu", 
  Jigglypuff = "Jigglypuff", 
  Mewtwo = "Mewtwo", 
  GAW = "Mr. Game & Watch", 
  Marth = "Marth", 
  Roy = "Roy"
}